name: Mypy Checks
on: [pull_request, commit]

jobs:
  build:
    runs-on: ubuntu-latest
    name: mypy
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - run: mypy .
